version: '3.8'

services:
  samba:
    image: dperson/samba:latest
    ports:
      - target: 445
        published: 445
        mode: host
      - target: 139
        published: 139
        mode: host
    environment:
      # ============================================
      # Users: -u "username;password"
      # ============================================
      - USER=luggie;LuggieSecure123
      - USER2=emi;EmiSecure123
      - USER3=lele;LeleSecure123
      - USER4=riri;RiriSecure123
      - USER5=nasadm;AdminSecure123
      
      # ============================================
      # Shares: -s "name;path;browseable;readonly;guest;users;admins"
      # ============================================
      
      # USB NAS Shares (Family Data)
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      
      # Shared: Alle Family Members können lesen/schreiben
      - SHARE=shared;/usb/shared;yes;no;no;luggie,emi,lele,riri,nasadm;nasadm;0777;0777
      
      # Private: Nur Owner + nasadm
      - SHARE2=luggie;/usb/luggie;yes;no;no;luggie,nasadm;nasadm;0777;0777
      - SHARE3=emi;/usb/emi;yes;no;no;emi,nasadm;nasadm;0777;0777
      - SHARE4=lele;/usb/lele;yes;no;no;lele,nasadm;nasadm;0777;0777
      - SHARE5=riri;/usb/riri;yes;no;no;riri,nasadm;nasadm;0777;0777
      
      # GlusterFS Share (Admin/Scripts)
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      
      # Storage: Nur nasadm (für scripts, webapp, docker configs)
      - SHARE6=storage;/gluster;yes;no;no;nasadm;nasadm;0777;0777
      
      # Workgroup
      - WORKGROUP=WORKGROUP
      
    volumes:
      # USB NAS Data (funktioniert auf beiden Nodes via Symlink)
      # pi-3: /mnt/usb-nas-master -> real path
      # pi-4: /mnt/usb-nas-master -> symlink to /mnt/usb-nas-backup
      - /mnt/usb-nas-master/data:/usb:rw
      
      # GlusterFS (auf beiden Nodes gleich gemountet)
      - /mnt/glusterfs-swarm:/gluster:rw
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          # Läuft auf pi-3 (hat USB + GlusterFS)
          - node.hostname == zolo-pi-3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - nas

networks:
  nas:
    driver: overlay